### ISSUE TITLE
Does the open-source myscaledb v1.4 version support multi node deployment?

### ISSUE THREAD

**Issue by luckercs** [myscale/myscaledb#26]
Does the open-source version of myscaledb v1.4 support multi node cluster deployment? 

Is scalability currently only supported for single machine deployment? 

Additionally, does the open source version support MSTG?

Because it was mentioned in the released documentation that the open-source version only supports vertical scaling, I would like to confirm again whether it supports horizontal scaling with multiple nodes.

If supported, is the horizontal scaling method the same as clickhouse?

**Comment by lqhl** [comment]
1. MyScaleDB, being a fork of ClickHouse, supports high availability through the use of [ReplicatedMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication) and scalability via the [Distributed Table Engine](https://clickhouse.com/docs/en/engines/table-engines/special/distributed). Both features have been thoroughly tested.
2. The MSTG feature is exclusively offered in [MyScale Cloud](https://myscale.com) and is not open-source.
