### ISSUE TITLE
Can not build this project

### ISSUE THREAD

**Issue by t7485752** [myscale/myscaledb#27]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**  Rocky8.9

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**  3.26

**Ninja version** 

**Compiler name and version** GCC 13

**Full cmake and/or ninja output**

[submodule "rust/supercrate/libs/tantivy_search"]
	path = rust/supercrate/libs/tantivy_search
	url = git@git.moqi.ai:mqdb/tantivy-search.git

This submodule seems a internal repo and can not clone code to my laptop computer, so how can I build myscaledb, need help.

**Comment by Aed-p** [comment]
It seems that you are using the unreleased myscale 1.5 version, which has not yet been officially released. However, the latest commit has made tantivy_search public, you can try again
