### ISSUE TITLE
Cluster Still there

### ISSUE THREAD

**Issue by usamajamil43** [myscale/MyScaleDB#34]
I created a cluster a few days back and I got an email that my cluster was terminated, but I can still the cluster and I can also get the details but when I try to access the cluster using details, I get an error. I tried multiple times, but the error was still there and the cluster remained idle.

The issue is: If the system has emailed me that my cluster is terminated, then it shouldn't show anything on the website.

I got this email:
<img width="739" alt="cluster_terminated_email" src="https://github.com/myscale/MyScaleDB/assets/50251867/19dbd470-92d5-4363-b13c-171ed34111d5">

But the cluster was still there:

<img width="888" alt="cluster_still_there" src="https://github.com/myscale/MyScaleDB/assets/50251867/0e31436b-21a1-4d0c-a797-c0f68f242267">

I tried to access it but Couldn't:

<img width="828" alt="errorr" src="https://github.com/myscale/MyScaleDB/assets/50251867/722aac67-99e3-44e8-b0d4-2ec74c171072">

**Comment by lqhl** [comment]
@usamajamil43 Our engineer has inspected the issue. It appears that your cluster named `gemini` has been terminated. Did you start a new cluster afterward? Please note that free pods will stop if they are idle and may take some time to automatically resume.

**Comment by usamajamil43** [comment]
I tried again, created new clusters, waited 7 days and now everything is working fine
