### ISSUE TITLE
how to do sql range query in metadata filtering

### ISSUE THREAD

**Issue by Rohith-Scalers** [myscale/MyScaleDB#39]
how to do sql range query in metadata filtering

**Comment by feixue1121** [comment]
hi Scalers, 

Following is an example using id column as a range filter to filter rows.
--------------------------------------------------------------
SELECT id, date, label, 
    distance(vector_column, {target_vector}) as dist 
FROM default.myscale_categorical_vector_search 
WHERE id > 2 and id < 5 
ORDER BY dist 
LIMIT 10
--------------------------------------------------------

**Comment by Rohith-Scalers** [comment]
Thank you , how can i use this filtered data as a index to do vector search

**Comment by Rohith-Scalers** [comment]
Thank you :)
