### ISSUE TITLE
do i need to recrate the entire index if there is continues ingestion ? 

### ISSUE THREAD

**Issue by Rohith-Scalers** [myscale/MyScaleDB#40]
do i need to recrate the entire index if there is continues ingestion ? can i directly insert the embeddings and do distance search with out making a index ?  please let me know if there are any examples with continues ingestion to database.

**Comment by lqhl** [comment]
Yes, if you have created a vector index, you can insert vectors and search for them directly. The db will build index for new data automatically. Before the index was built, db will search new data using the brute force method, so the insert may degrade the search performance.

**Comment by Rohith-Scalers** [comment]
Thank you :) , it was helpful
